[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]

[profile.dev]
opt-level = 1
debug = 2
incremental = true

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
incremental = false
