[alias]
check-ci = "check --workspace --all-features --all-targets"
cov = "llvm-cov --workspace --all-features --html --output-dir ./coverage --open"
cov-ci = "llvm-cov --workspace --all-features --lcov --output-path ./coverage/lcov.txt"
cov-summary = "llvm-cov --workspace --all-features --summary-only --output-path ./coverage/summary.txt"
docs = "doc --workspace --all-features --no-deps"
format = "fmt --all"
format-ci = "fmt --all -- --check"
lint = "clippy --workspace --all-features --all-targets --fix --allow-dirty --allow-staged -- -D warnings"
lint-ci = "clippy --workspace --all-features --all-targets -- -D warnings"
tests = "test --workspace --all-features --all-targets -- --nocapture"
