name: changelog
on:
    workflow_run:
        workflows: [ tests ]
        types: [ completed ]
        branches: [ main ]
jobs:
    changelog:
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            -   uses: actions/checkout@v4
                with: { fetch-depth: 0 }
            -   id: guard
                name: Skip if commit is the changelog-only merge
                shell: bash
                run: |
                    msg="$(git log -1 --pretty=%s)"
                    files="$(git show --pretty="" --name-only)"
                    echo "commit: $msg"
                    echo "files: $files"
                    if [[ "$msg" == "chore: update `changelog.md`" ]] || [[ "$files" == "changelog.md" ]]; then
                      echo "skip=true" >> "$GITHUB_OUTPUT"
                    else
                      echo "skip=false" >> "$GITHUB_OUTPUT"
                    fi
            -   name: Generate changelog
                if: ${{ steps.guard.outputs.skip == 'false' }}
                uses: orhun/git-cliff-action@v4
                with:
                    config: cliff.toml
                env:
                    OUTPUT: changelog.md
            -   name: Create Pull Request
                if: ${{ steps.guard.outputs.skip == 'false' }}
                uses: peter-evans/create-pull-request@v6
                with:
                    base: main
                    branch: chore/update-changelog
                    commit-message: "chore: update `changelog.md`"
                    title: "chore: update `changelog.md`"
                    body: "Automated changelog update after CI success."
                    add-paths: |
                        changelog.md
